#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

stage=-1
stop_stage=100

root_dir=/star-home/jinzengrui/data/libritts/LibriTTS

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: prepare wav list files"
  mkdir -p data/wav_list
  python3 ./local/prepare_wav_list.py --root-dir $root_dir --out-dir data/wav_list

  cat data/wav_list/train-clean-100.txt data/wav_list/train-clean-360.txt \
    data/wav_list/train-other-500.txt > data/wav_list/train-full-960.txt
fi


